title: Ashley Levy # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://public.tableau.com/app/profile/ashley.levy8624>Tableau Public</a>
  <br><br>
  <a href="https://www.kaggle.com/ashleylevy">Kaggle</a>
  <br><br>
  <a href="www.linkedin.com/in/ashley-levy/">LinkedIn</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
