title: Ashley Levy # your name (or website title) here
logo: 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Former special education teacher turned data analyst with a passion for leveraging data to optimize performance, skilled in R, SQL, and Tableau.
  <br><br>
  I am actively seeking remote or hybrid job opportunities in the Metro Atlanta area to apply my skills and contribute to organizations in a flexible work environment.
  <br><br>
  <a href="https://www.linkedin.com/in/ashley-levy/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
